"""empty message

Revision ID: 6b8592f94d99
Revises: 7a55367d1628
Create Date: 2024-12-09 03:14:05.185429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8592f94d99'
down_revision = '7a55367d1628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('country')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
