"""empty message

Revision ID: a48b7fb6211b
Revises: c488877f254b
Create Date: 2024-12-18 18:56:16.002590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48b7fb6211b'
down_revision = 'c488877f254b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_profile', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('photo_profile')

    # ### end Alembic commands ###
